# Default values for nsfactory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace name to use for the namespace. If not provided, the namespace will be named after the owner and environment.
#namespace: namespace-name
# Owner of the namespace.
owner: example
# Environment of the namespace.
environment: example

# Resources for the namespace.
resources:
  quota:
    cpuRequests: 1
    cpuLimits: 2
    memoryRequests: 1Gi
    memoryLimits: 2Gi
  limits:
    defaultCpu: 500m
    defaultMemory: 512Mi
    defaultRequestCpu: 200m
    defaultRequestMemory: 256Mi

# RBAC bindings for the namespace.
# rbac:
# adminGroup: example-admins
# viewGroup: example-viewers