apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-factory
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/JoeyJoHa/GitOps-Namespace-Factory.git
      revision: HEAD
      files:
      - path: "tenants/*.yaml"
  template:
    metadata:
      name: '{{ default (printf "%s-%s" .owner .environment) (index . "namespace") }}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/JoeyJoHa/GitOps-Namespace-Factory.git
        targetRevision: HEAD
        path: 'helm/nsfactory'
        helm:
          valueFiles:
            - '/{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default (printf "%s-%s" .owner .environment) (index . "namespace") }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true