apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factory-apps
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JoeyJoHa/GitOps-Namespace-Factory.git
    targetRevision: HEAD
    path: openshift-gitops/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      enabled: true