apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-factory
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/JoeyJoHa/GitOps-Namespace-Factory.git
      revision: HEAD
      files:
      - path: "tenants/*.yaml"
  template:
    metadata:
      name: '{{metadata.namespace}}'
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/JoeyJoHa/GitOps-Namespace-Factory.git
        targetRevision: HEAD
        path: 'helm/nsfactory'
        helm:
          valueFiles:

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{metadata.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true