apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-apps
  namespace: argocd
spec:
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: argoproj.io
    kind: ApplicationSet
  - group: argoproj.io
    kind: AppProject
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  sourceRepos:
  - https://github.com/JoeyJoHa/GitOps-Namespace-Factory.git