apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "nsfactory.LimitRange" . }}
  namespace: {{ include "nsfactory.Namespace" . }}
  labels:
    owner: {{ .Values.owner }}
    environment: {{ .Values.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
    - type: Container
      default: 
        cpu: {{ .Values.resources.limits.defaultCpu }}
        memory: {{ .Values.resources.limits.defaultMemory }}
      defaultRequest: 
        cpu: {{ .Values.resources.limits.defaultRequestCpu }}
        memory: {{ .Values.resources.limits.defaultRequestMemory }}
      
