kind: Namespace
apiVersion: v1
metadata:
  name: {{ include "nsfactory.Namespace" . }}
  labels:
    owner: {{ .Values.owner }}
    environment: {{ .Values.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"