---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "nsfactory.ResourceQuota" . }}
  namespace: {{ include "nsfactory.Namespace" . }}
  labels:
    owner: {{ .Values.owner | include "nsfactory.K8SObjectName" }}
    environment: {{ .Values.environment | include "nsfactory.K8SObjectName" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: {{ .Values.resources.quota.cpuRequests }}
    requests.memory: {{ .Values.resources.quota.memoryRequests }}
    limits.cpu: {{ .Values.resources.quota.cpuLimits }}
    limits.memory: {{ .Values.resources.quota.memoryLimits }}